-- Eventful + Agentic Ops shared schema.
--
-- Apply with:
--   psql "$DATABASE_URL" -f infra/scripts/init_db.sql
--
-- Designed to mirror the file-based contract (data/event_state.json +
-- data/ranked_people.csv + logs/agent_runs.jsonl). Both branches read/write
-- through this schema.
--
-- Notes:
-- * Loose, fast-iterating fields go in JSONB columns so we don't ship a
--   migration every time the audience designer adds a new key.
-- * Append-only agent_runs table replaces logs/agent_runs.jsonl.
-- * unique(event_id, linkedin_url) lets the curator re-run idempotently —
--   subsequent runs UPSERT the same person rather than duplicating.

create extension if not exists "uuid-ossp";

-- =====================================================================
-- events
-- =====================================================================
create table if not exists events (
    id              uuid primary key default uuid_generate_v4(),
    name            text not null,
    goal            text,
    city            text,
    event_date      date,
    target_size     int,
    format          text,
    brief_text      text,                  -- raw event proposal
    success_metrics jsonb default '[]'::jsonb,
    intelligence    jsonb default '{}'::jsonb,  -- audience_icp, avoid, rubric, room_balance
    state           jsonb default '{}'::jsonb,  -- open_questions, blockers, next_actions
    visibility      jsonb default '{}'::jsonb,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index if not exists events_created_at_idx on events (created_at desc);

-- =====================================================================
-- people (prospects per event)
-- =====================================================================
create table if not exists people (
    id              uuid primary key default uuid_generate_v4(),
    event_id        uuid not null references events(id) on delete cascade,
    name            text not null,
    company         text,
    role            text,
    linkedin_url    text,
    email           text,
    persona         text,
    fit_score       int,
    priority        text,                  -- high | medium | low | needs_review
    why_relevant    text,
    tags            text[] default '{}'::text[],
    status          text default 'not_contacted',
    source          text,
    outreach_angle  text,
    notes           text,
    raw             jsonb default '{}'::jsonb,  -- catch-all for fields added later
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),

    -- An empty linkedin_url means we haven't found one yet — treat empty as
    -- non-conflicting. Use a partial unique index so only non-empty URLs are
    -- enforced unique per event.
    unique (event_id, name, company)
);

create unique index if not exists people_event_linkedin_idx
    on people (event_id, linkedin_url)
    where linkedin_url is not null and linkedin_url <> '';

create index if not exists people_event_priority_idx
    on people (event_id, priority);

create index if not exists people_event_persona_idx
    on people (event_id, persona);

create index if not exists people_event_fit_idx
    on people (event_id, fit_score desc);

-- =====================================================================
-- agent_runs (append-only visibility trace)
-- =====================================================================
create table if not exists agent_runs (
    id                uuid primary key default uuid_generate_v4(),
    run_id            text not null,         -- generated by visibility.create_run_id()
    event_id          uuid references events(id) on delete cascade,
    branch_context    text not null,         -- "event_intelligence" | "agentic_ops"
    agent_name        text not null,
    input_summary     text,
    output_summary    text,
    decisions_made    jsonb default '[]'::jsonb,
    reasoning_summary text,
    confidence        text,
    files_read        text[] default '{}'::text[],
    files_written     text[] default '{}'::text[],
    blockers          jsonb default '[]'::jsonb,
    next_actions      jsonb default '[]'::jsonb,
    created_at        timestamptz not null default now()
);

create index if not exists agent_runs_event_idx on agent_runs (event_id, created_at desc);
create index if not exists agent_runs_agent_idx on agent_runs (agent_name, created_at desc);
create index if not exists agent_runs_run_id_idx on agent_runs (run_id);

-- =====================================================================
-- updated_at triggers
-- =====================================================================
create or replace function set_updated_at() returns trigger as $$
begin new.updated_at = now(); return new; end;
$$ language plpgsql;

drop trigger if exists events_set_updated_at on events;
create trigger events_set_updated_at before update on events
    for each row execute function set_updated_at();

drop trigger if exists people_set_updated_at on people;
create trigger people_set_updated_at before update on people
    for each row execute function set_updated_at();
